# Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# Gradle
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.isolated-projects=false
org.gradle.jvmargs=-Xmx8G -XX:+UseParallelGC -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx8G"
org.gradle.parallel=true
org.gradle.tooling.parallel=true
# Kotlin
kotlin.code.style=official
kotlin.incremental=true
kotlin.js.compiler=ir
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
# Android
klibs.android.sdk.min=21
klibs.android.sdk.target=36
klibs.android.sdk.compile=36
# Java
klibs.java.source=8
klibs.java.target=17
klibs.java.ktarget=17
# Project
klibs.project.name=KStorage
klibs.project.group=ru.astrainteractive.klibs
klibs.project.version.string=5.4.0
klibs.project.description=Kotlin wrapper for key-value storage libraries
klibs.project.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
klibs.project.url=https://github.com/makeevrserg/klibs.kstorage/
# Publish
klibs.publish.repo.name=klibs.kstorage
klibs.publish.groupId=ru.astrainteractive.klibs
klibs.publish.description=Kotlin wrapper for key-value storage libraries
klibs.publish.repo.org=makeevrserg
klibs.publish.name=klibs.kstorage
klibs.publish.license=Apache-2.0
klibs.publish.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
